#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-docker-compose.generated.yml}"

if [[ "$OUTPUT" != /* ]]; then
  OUTPUT="$ROOT_DIR/$OUTPUT"
fi

case "$OUTPUT" in
  "$ROOT_DIR"/*) ;;
  *)
    echo "error: output must be under $ROOT_DIR" >&2
    exit 1
    ;;
esac

if [[ ! -f "$ROOT_DIR/docker-compose.yml" ]]; then
  echo "error: $ROOT_DIR/docker-compose.yml not found" >&2
  exit 1
fi

mapfile -t WEB_FILES < <(
  find "$ROOT_DIR" -maxdepth 2 -mindepth 2 -type f -name web-compose.yml | sort
)

tmp_file="$(mktemp)"
{
  echo "# Generated by $(basename "$0"). Do not edit."
  echo "include:"
  echo "  - ./docker-compose.yml"
  for file in "${WEB_FILES[@]}"; do
    rel="${file#$ROOT_DIR/}"
    echo "  - ./$rel"
  done
} > "$tmp_file"

mv "$tmp_file" "$OUTPUT"
echo "wrote $OUTPUT"
